apiVersion: v1
kind: Pod
metadata:
 name: order-pod
 labels:
  app: order
spec:
 containers:
 - name: order-container
   image: anmol4210/order:v2
   env:
    - name: jaggerURL
      value: "10.125.4.47"